on:
  workflow_dispatch:

jobs:
  r_barcs_webscarping_run:
    name: Run BARCS webscaping
    runs-on: ubuntu-latest
    #runs-on: macos-latest
    container: rocker/verse
    steps:
    
      - name: Checkout 
        uses: actions/checkout@v2
        
      #- name: setup R 
      #  uses: r-lib/actions/setup-r@master
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      #- name: Setup Firefox
      #  uses: browser-actions/setup-firefox@v0.0.0

      #- run: firefox --version 

      - name: Run RScript
        run: Rscript R/barcs_webscraping_test.R
        env: 
          github_pat_value: ${{ secrets.PAT_BARCS }}


    
